version: '2'
services:
  web:
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:9
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
